### ISSUE TITLE
Census2016 packages

### ISSUE THREAD

**Issue by HughParsonage** [RConsortium/censusguide#10]
Hello, as the author and maintainer of the [Census2016](https://github.com/hughparsonage/Census2016.Datapack) family of packages, I wish to draw your attention to them. They relate to the Australian Census so slightly off-topic if only for the US Census data, but you might find it useful.

**Comment by arilamstein** [comment]
Hi @HughParsonage - thank you for letting me know about the `Census2016` family of packages.

This project is - for better or for worse - focused exclusively on US Census Data. In order to understand why, it might help to know a bit about the history of this project.

Last year I contracted with the US Census Bureau to develop a short course on using R to analyze US Census Data. That course is going to be published on [Census Academy](https://www.census.gov/academy), their new online training platform, sometime later this year. The course teaches people how to use a single R package, `choroplethr`, to explore the American Community Survey.

When @joseph-rickert (a director at the [R Consortium](https://www.r-consortium.org/)) learned about this project, he recommended that I apply to the R Consortium for funding to do a followup project. When he reached out to me I already had a project in mind: doing a survey of R packages that work with US Census Data. 

I'm the author of `choroplethr`, so it made sense for me to use it to teach an "Intro to Using R to Analyze Census Data" course. But it always bothered me that I was teaching people how to use my own package, as opposed to giving a comprehensive overview of the R ecosystem on that exists for working with Census Data. This project is designed to address that problem.
